spring.application.name=ticket2cash

server.port=3000

# Base H2 en mémoire pour le MVP
spring.datasource.url=jdbc:h2:file:C:/Users/PC/Desktop/dev/ticket2cash/data/ticket2cashdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true